<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'You have really very <strong>old</strong> web browser. Please <a
	href="http://browsehappy.com/">upgrade</a> or <a href="http://www.google.com/chromeframe/?redirect=true">activate
	Google Chrome Frame</a> for better experience.' => 'Máte opravdu hodně <strong>starý</strong> webový prohlížeč. Prosíme <a href="http://browsehappy.com/">nainstalujte si</a> jeho vyšší verzi nebo <a href="http://www.google.com/chromeframe/?redirect=true">si aktivujte Google Chrome Frame</a> pro lepší zážitky.',
    'email' => 'email',
    'message' => 'zpráva',
    'name' => 'jméno',
    'subject' => 'předmět',
    'to top' => 'nahoru',
];
